### PR TITLE
REFACTORING: `/corpus/:x` and `/item/:x/:y` APIs are not used anymore.

### PR DESCRIPTION
**Pull request by benel**
I'm really sorry I cannot assure it works.

I spent more than 1 hour on "pushapps" in vain. :'( 
I cannot understand why I cannot push multiple design documents on my machine.

### CODE REVIEW

**Comment by christophe-lejeune** [comment]
This new code works nice on my test machine. 

May I suggestion that you remove the version number (first line) from the `docker-compose.yml` ? Indeed the version attribute is removed from modern version of `docker compose`.

**Comment by benel** [comment]
> the version attribute is removed from modern version of docker compose.

Indeed. I kept it only in case you would need it.

> May I suggest that you remove the version attribute (first line) from the docker-compose.yml? 

OK, I will amend my commit.

**Comment by benel** [comment]
> OK, I will amend my commit.

Hmm, it's not really related. Maybe preferable to create a new commit?

**Comment by benel** [comment]
@christophe-lejeune

**Comment by christophe-lejeune** [comment]
This pull request was integrated through 73230439864a1851972dd1f99cc830743f345816 and f570fea8b4145a10afbf04c5bf8fe5733d8778da.

**Pull request closed without merging**
